
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: gateway-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default: http://localhost:8761/eureka/
